### ISSUE TITLE
CPU/GPU usage not working, "Server is not running" spam in console.

### ISSUE THREAD

**Issue by Yomorabi** [Lukium/palworld-admin#6]
After starting a palworld server, the CPU and GPU usage are not working and a "Server is not running" message in printed every 5 seconds in the console, even though the palworld server and RCON are operational.

![server_not_running](https://github.com/Lukium/palworld-admin/assets/68148124/d028a45b-b101-44ab-8a6c-ccaded632f04)

I'm using version 0.6.3

**Comment by Yomorabi** [comment]
Update for version 0.6.4: Palworld admin is starting multiple instances of the server.

![image](https://github.com/Lukium/palworld-admin/assets/68148124/ab89d0a4-9497-4fea-8dc0-65524f53a84a)

**Comment by Lukium** [comment]
> Update for version 0.6.4: Palworld admin is starting multiple instances of the server.
> 
> ![image](https://private-user-images.githubusercontent.com/68148124/304623768-ab89d0a4-9497-4fea-8dc0-65524f53a84a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4ODk2NjcsIm5iZiI6MTcwNzg4OTM2NywicGF0aCI6Ii82ODE0ODEyNC8zMDQ2MjM3NjgtYWI4OWQwYTQtOTQ5Ny00ZmVhLThkYzAtNjU1MjRmNTNhODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDA1NDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZmY1M2Q1NWI2NzA4MDFiYmY5MzdjNjYyYjA4MWE5Mjk3ZmVjNTM3MmJhMDhhNGI1Y2NlMzJiZjcyMzg2YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yNEujHaQU3Dwf49Zd5aSj5NSOik109ixf3p8OPCDjEM)

can you get me some more info on the steps to reproduce it?

**Comment by Yomorabi** [comment]
> > Update for version 0.6.4: Palworld admin is starting multiple instances of the server.
> > ![image](https://private-user-images.githubusercontent.com/68148124/304623768-ab89d0a4-9497-4fea-8dc0-65524f53a84a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4ODk2NjcsIm5iZiI6MTcwNzg4OTM2NywicGF0aCI6Ii82ODE0ODEyNC8zMDQ2MjM3NjgtYWI4OWQwYTQtOTQ5Ny00ZmVhLThkYzAtNjU1MjRmNTNhODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDA1NDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZmY1M2Q1NWI2NzA4MDFiYmY5MzdjNjYyYjA4MWE5Mjk3ZmVjNTM3MmJhMDhhNGI1Y2NlMzJiZjcyMzg2YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yNEujHaQU3Dwf49Zd5aSj5NSOik109ixf3p8OPCDjEM)
> 
> can you get me some more info on the steps to reproduce it?

1. I start Palworld admin by double clicking it.
2. I go to the Local Server Manager section.
3. I click on the green Start button.
4. RCON is connected automatically.
5. I get a notification that the server is not running.
6. A new server instance is created every few seconds after that.


Settings are default except for server name, server password, description, IP, RCON password.

**Comment by Lukium** [comment]
> > > Update for version 0.6.4: Palworld admin is starting multiple instances of the server.
> > > ![image](https://private-user-images.githubusercontent.com/68148124/304623768-ab89d0a4-9497-4fea-8dc0-65524f53a84a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4ODk2NjcsIm5iZiI6MTcwNzg4OTM2NywicGF0aCI6Ii82ODE0ODEyNC8zMDQ2MjM3NjgtYWI4OWQwYTQtOTQ5Ny00ZmVhLThkYzAtNjU1MjRmNTNhODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDA1NDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZmY1M2Q1NWI2NzA4MDFiYmY5MzdjNjYyYjA4MWE5Mjk3ZmVjNTM3MmJhMDhhNGI1Y2NlMzJiZjcyMzg2YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yNEujHaQU3Dwf49Zd5aSj5NSOik109ixf3p8OPCDjEM)
> > 
> > 
> > can you get me some more info on the steps to reproduce it?
> 
> 1. I start Palworld admin by double clicking it.
> 2. I go to the Local Server Manager section.
> 3. I click on the green Start button.
> 4. RCON is connected automatically.
> 5. I get a notification that the server is not running.
> 6. A new server instance is created every few seconds after that.
> 
> Settings are default except for server name, server password, description, IP, RCON password.

I seem to have one more user experiencing something similar. I strongly believe that it has something to do with Windows Localization. Would you be willing to hop on Discord to see if we can work together to figure out a good workaround for this?

For more details, the app runs a Powershell command to try and detect that the server is running by checking for its CPU/RAM usage. I have already written a workaround that I thought worked for all languages, but clearly, it doesn't seem to work for **ALL** languages (though it does work for most).

**Comment by Lukium** [comment]
> I have the logs from version 0.7.1. [log-0.7.1.txt](https://github.com/Lukium/palworld-admin/files/14291480/log-0.7.1.txt)

Should be fixed on 0.7.2, please let me know :)

**Comment by Yomorabi** [comment]
> > I have the logs from version 0.7.1. [log-0.7.1.txt](https://github.com/Lukium/palworld-admin/files/14291480/log-0.7.1.txt)
> 
> Should be fixed on 0.7.2, please let me know :)

Still happening in 0.7.2
![image](https://github.com/Lukium/palworld-admin/assets/68148124/805e5792-6755-4106-bddf-46558fb19491)

**Comment by Lukium** [comment]
> > > I have the logs from version 0.7.1. [log-0.7.1.txt](https://github.com/Lukium/palworld-admin/files/14291480/log-0.7.1.txt)
> > 
> > 
> > Should be fixed on 0.7.2, please let me know :)
> 
> Still happening in 0.7.2 ![image](https://private-user-images.githubusercontent.com/68148124/305293762-805e5792-6755-4106-bddf-46558fb19491.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTUwMDIsIm5iZiI6MTcwODA5NDcwMiwicGF0aCI6Ii82ODE0ODEyNC8zMDUyOTM3NjItODA1ZTU3OTItNjc1NS00MTA2LWJkZGYtNDY1NThmYjE5NDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE0NDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNGMzMGMzMWE4NGI4MDc3NmY2NGY2MWQyZDg5MjJiY2MzYjQ4MGI2ZWY5YWQ3NDdkZGM5ZWY4NmQwMzU5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-jS2gYYkn1kHJYfNIgzMTaMSnGOErB2iA8ydk807qdw)

can you run the command from the log in powershell and provide what it returns?
```Powershell
$PN = "PalServer-Win64-Test-Cmd"; Get-CimInstance 
Win32_PerfFormattedData_PerfProc_Process | Where-Object { $_.Name -eq $PN } | Select-Object -Property Name, 
PercentProcessorTime, WorkingSet -First 1 | ForEach-Object { $cpuUsage = $_.PercentProcessorTime; $workingSetSize = 
$_.WorkingSet; "$cpuUsage $workingSetSize" }
```
The issue seems to be arising from neither the Get-Counter or the Get-CimInstance being able to get information on the server

**Comment by Yomorabi** [comment]
> can you run the command from the log in powershell while the dedicated server is running and provide what it returns?
> 
> ```powershell
> $PN = "PalServer-Win64-Test-Cmd"; Get-CimInstance 
> Win32_PerfFormattedData_PerfProc_Process | Where-Object { $_.Name -eq $PN } | Select-Object -Property Name, 
> PercentProcessorTime, WorkingSet -First 1 | ForEach-Object { $cpuUsage = $_.PercentProcessorTime; $workingSetSize = 
> $_.WorkingSet; "$cpuUsage $workingSetSize" }
> ```
> 
> The issue seems to be arising from neither the Get-Counter or the Get-CimInstance being able to get information on the server

I get this error message:
```
Get-CimInstance : Classe non valide
Au caractère Ligne:1 : 35
+ ... -Test-Cmd"; Get-CimInstance Win32_PerfFormattedData_PerfProc_Process  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2:Win3...erfProc_Process:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
```

**Comment by Lukium** [comment]
> > can you run the command from the log in powershell while the dedicated server is running and provide what it returns?
> > ```powershell
> > $PN = "PalServer-Win64-Test-Cmd"; Get-CimInstance 
> > Win32_PerfFormattedData_PerfProc_Process | Where-Object { $_.Name -eq $PN } | Select-Object -Property Name, 
> > PercentProcessorTime, WorkingSet -First 1 | ForEach-Object { $cpuUsage = $_.PercentProcessorTime; $workingSetSize = 
> > $_.WorkingSet; "$cpuUsage $workingSetSize" }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The issue seems to be arising from neither the Get-Counter or the Get-CimInstance being able to get information on the server
> 
> I get this error message:
> 
> ```
> Get-CimInstance : Classe non valide
> Au caractère Ligne:1 : 35
> + ... -Test-Cmd"; Get-CimInstance Win32_PerfFormattedData_PerfProc_Process  ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : MetadataError: (root\cimv2:Win3...erfProc_Process:String) [Get-CimInstance], CimException
>     + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
> ```

So, it appears that your version of Windows can't run that command... I'll have to look into an alternative.
